# Generated by Django 5.2 on 2025-05-06 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_bill_employee_name_alter_bill_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_tax_rate', models.DecimalField(decimal_places=4, default=0.0825, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.RemoveField(
            model_name='billlineitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='billlineitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='billlineitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='is_labor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='part_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.technician'),
        ),
        migrations.AddField(
            model_name='technician',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=85.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
