# Generated by Django 5.2 on 2025-05-06 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_billlineitem_employee_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('font', models.CharField(choices=[('Roboto', 'Roboto'), ('Arial', 'Arial'), ('Lato', 'Lato'), ('Open Sans', 'Open Sans'), ('Montserrat', 'Montserrat'), ('Source Sans Pro', 'Source Sans Pro'), ('Nunito', 'Nunito'), ('Raleway', 'Raleway'), ('Ubuntu', 'Ubuntu'), ('Merriweather', 'Merriweather'), ('Inter', 'Inter'), ('Georgia', 'Georgia')], default='Roboto', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
