# Generated by Django 5.2 on 2025-05-07 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.055, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
